import type { NextPage } from 'next'
import Head from 'next/head'
import { VStack } from '@chakra-ui/react';
import { Header } from '../components/Header';
import { NavMenu } from '../components/NavMenu';
import { Main } from '../components/Main';

const Home: NextPage = () => {
  return (
    <VStack spacing={0}>
      <Head>
        <title>Livraria Virtual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <NavMenu />
      <Main />
    </VStack>
  )
}

export default Home
