import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import { Heading, VStack } from '@chakra-ui/react';
import { Header } from '../components/Header';

const Home: NextPage = () => {
  return (
    <VStack>
      <Head>
        <title>Livraria Virtual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <Header />
    </VStack>
  )
}

export default Home
